name: Build OpenCV
on:
  push:
    tags:
      - '*'
  workflow_dispatch: []

jobs:
  build:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        buildx_arch: [linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set env
        run: echo "BA_TAG=$(echo '${{ matrix.buildx_arch }}' | rev | cut -d "/" -f 1 | rev)" >> $GITHUB_ENV
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            ghcr.io/suika/opencv-video-minimal
            suika/opencv-video-minimal
          flavor: |
            latest=false
          labels: |
            org.opencontainers.image.title=opencv
            org.opencontainers.image.vendor=suika
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: "--debug"
      -
        name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build against ${{ env.BA_TAG }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          file: ./Dockerfile
          tags: ghcr.io/suika/opencv-video-minimal:${{ env.BA_TAG }},suika/opencv-video-minimal:${{ env.BA_TAG }}
          platforms: ${{ matrix.buildx_arch }}
          labels: ${{ steps.docker_meta.outputs.labels }}
        env:
          buildx_arch_var: ${{ matrix.buildx_arch }}
  manifest:
    runs-on: [ubuntu-latest]
    needs: [build]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Extract version metadata
        id: meta
        run: |
          echo "::set-output name=version::${GITHUB_REF##*/}"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: "--debug"
      -
        name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Create manifest
        run: |
          docker manifest create ghcr.io/suika/opencv-video-minimal:${{ steps.meta.outputs.version }} \
            ghcr.io/suika/opencv-video-minimal:amd64 \
            ghcr.io/suika/opencv-video-minimal:386 \
            ghcr.io/suika/opencv-video-minimal:v6 \
            ghcr.io/suika/opencv-video-minimal:v7 \
            ghcr.io/suika/opencv-video-minimal:arm64
          docker manifest create ghcr.io/suika/opencv-video-minimal:latest \
            ghcr.io/suika/opencv-video-minimal:amd64 \
            ghcr.io/suika/opencv-video-minimal:386 \
            ghcr.io/suika/opencv-video-minimal:v6 \
            ghcr.io/suika/opencv-video-minimal:v7 \
            ghcr.io/suika/opencv-video-minimal:arm64
          docker manifest create suika/opencv-video-minimal:${{ steps.meta.outputs.version }} \
            suika/opencv-video-minimal:amd64 \
            suika/opencv-video-minimal:386 \
            suika/opencv-video-minimal:v6 \
            suika/opencv-video-minimal:v7 \
            suika/opencv-video-minimal:arm64
          docker manifest create suika/opencv-video-minimal:latest \
            suika/opencv-video-minimal:amd64 \
            suika/opencv-video-minimal:386 \
            suika/opencv-video-minimal:v6 \
            suika/opencv-video-minimal:v7 \
            suika/opencv-video-minimal:arm64
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
      -
        name: Push manifest
        run: |
            docker manifest push ghcr.io/suika/opencv-video-minimal:${{ steps.meta.outputs.version }}
            docker manifest push ghcr.io/suika/opencv-video-minimal:latest
            docker manifest push suika/opencv-video-minimal:${{ steps.meta.outputs.version }}
            docker manifest push suika/opencv-video-minimal:latest
