name: buildx
on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  build:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        buildx_arch: [linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - 
        name: Docker login
        run: |
          docker login -u "${DOCKER_REGISTRY_USERNAME}" -p "${DOCKER_REGISTRY_PASSWORD}"
        env:
          DOCKER_REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Run Buildx ${{ matrix.buildx_arch }}
        run: |
          docker buildx build \
            --platform ${{ matrix.buildx_arch }} \
            --output "type=image,push=true" \
            --tag suika/opencv-video-minimal:${buildx_arch_var##*/} \
            --file Dockerfile .
        env:
          buildx_arch_var: ${{ matrix.buildx_arch }}
      - 
        name: Docker logout
        run: |
          docker logout
  manifest:
    runs-on: [ubuntu-latest]
    needs: [build]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - 
        name: Docker login
        run: |
          docker login -u "${DOCKER_REGISTRY_USERNAME}" -p "${DOCKER_REGISTRY_PASSWORD}"
        env:
          DOCKER_REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Create manifest
        run: |
          docker manifest create suika/opencv-video-minimal:4.2-py3.7.5 \
            suika/opencv-video-minimal:amd64 \
            suika/opencv-video-minimal:arm64 \
            suika/opencv-video-minimal:ppc64le \
            suika/opencv-video-minimal:s390x \
            suika/opencv-video-minimal:386 \
            suika/opencv-video-minimal:v7 \
      -
        name: Push manifest
        run: |
            docker manifest push suika/opencv-video-minimal:4.2-py3.7.5
      - 
        name: Docker logout
        run: |
          docker logout
