name: buildx
on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  build:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        buildx_arch: [linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - 
        name: Docker login
        run: |
          docker login -u "${DOCKER_REGISTRY_USERNAME}" -p "${DOCKER_REGISTRY_PASSWORD}" docker.pkg.github.com
        env:
          DOCKER_REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Run Buildx ${{ matrix.buildx_arch }}
        run: |
          docker buildx build \
            --platform ${{ matrix.buildx_arch }} \
            --output "type=image,push=true" \
            --tag docker.pkg.github.com/suika/opencv-video-minimal/opencv-video-minimal:latest \
            --file Dockerfile .
      - 
        name: Docker logout
        run: |
          docker logout
